title: Security Learning Environment & Homelab
description: A learning-focused environment for developing cybersecurity and infrastructure skills
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one