title: Mario Torres | Security & IT Professional
description: Portfolio and security lab documentation showcasing hands-on cybersecurity experience and technical projects
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
