title: 
description: Mario's homelab documentation.
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme